name: Test paper.yml for Each Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_config:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: # Liste der Server, die geprüft werden sollen
          - lobby
          - homerepublic
          - farmwelt

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Run Tests for paper.yml on ${{ matrix.server }}
      run: |
        echo "Testing paper.yml for server: ${{ matrix.server }}"

        # Baue das Docker-Image für den Testserver mit der paper.yml des jeweiligen Servers
        docker build --build-arg CONFIG=./${{ matrix.server }}/config/paper.yml -t minecraft-test-spielwiese:${{ matrix.server }} ./spielwiese

        # Starte den Testserver mit der Konfiguration
        docker run -d -p 25565:25565 --name ${matrix.server}-test-server minecraft-test-spielwiese:${{ matrix.server }}

        # Warte, bis der Server gestartet ist
        sleep 30

        # Überprüfe die Logs auf Fehler (nur Konfigurationsfehler)
        docker logs ${matrix.server}-test-server | grep -i 'error\|exception' && exit 1 || echo "Keine Fehler in der Konfiguration für ${matrix.server}"

        # Testserver aufräumen
        docker stop ${matrix.server}-test-server
        docker rm ${matrix.server}-test-server
